### ISSUE TITLE
<br> input results in <br><br> output

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/sitenow_wysiwyg#18]
```
<p><strong>Header</strong><br/>
Content goes here.</p>
```
results in the following output:
```
<p><strong>Header</strong><br><br>
Content goes here.</p>
```
![screen shot 2017-06-08 at 12 47 15 pm](https://user-images.githubusercontent.com/4663676/26942694-a62712e8-4c48-11e7-97ef-ba1ed2c4870d.png)

Editors can workaround the issue once by using:
```
<p><strong>Header</strong><br/>
Content goes here.</p>
```
in the HTML editor resulting in the following output:
![screen shot 2017-06-08 at 12 46 57 pm](https://user-images.githubusercontent.com/4663676/26942731-c6bfc504-4c48-11e7-9f06-16426ae86b56.png)

but the ending is stripped when edited again, or rich text is toggled.

**Comment by brandonneil** [comment]
On a site, I removed the WYSIWYG completely from filtered_html and manually saved the following:

```
<p>My test paragraph</p>
<p>A<br/>B</p>
```
Output:
```
<p>My test paragraph</p>
<p>A<br>B</p>
```

Saved a few times and no duplicates. So this tells me it isn't an issue with the text formatter. However, since `<br/>` is being transformed to `<br>` in the text format, it is possible that the WYSIWYG is now seeing that as the opening tag, and deciding to put a closing one in. Which in turn, gets the self-closure stripped on render.

**Comment by markahrens** [comment]
I had a customer report the issue as well. They were editing an existing page with line breaks and when saving, the duplicates were added in. I then manually changed the <br> to <br /> and when rendered, they were presented as <br>, duplicating what Brandon saw. The <br> is then presented when editing the page, causing the duplicates to come back again.

**Comment by joewhitsitt** [comment]
turning off `Convert line breaks into HTML (i.e. <br> and <p>)` caused my test example to render as expected with just one `<br>`.

the body_value in the database reveals extra stuff that would trigger the above functionality.
![screen shot 2017-06-09 at 1 45 37 pm](https://user-images.githubusercontent.com/4663676/26989781-f58def24-4d19-11e7-90ff-0a53ed36db8d.png)

**Comment by joewhitsitt** [comment]
Still not sure why this is happening all of a sudden, but maybe `Convert line breaks into HTML (i.e. <br> and <p>)` is no longer needed on formats with CKEditor, as CKEditor creates the necessary `<br>` and `<p>` tags based on soft and hard returns and moves the cursors appropriately.

https://drupal.stackexchange.com/questions/155593/ckeditor-adding-an-extra-br-tag-when-a-br-tag-is-encountered

Turning this off or moving it down in the processing order under `Correct faulty and chopped off HTML` seems to resolve the issue.

**Comment by joewhitsitt** [comment]
`<br />` and `<br/>` appear to be a non issue as it isn't html5 anyway:
https://stackoverflow.com/questions/1946426/html-5-is-it-br-br-or-br
