### ISSUE TITLE
Paste from word not working.

### ISSUE THREAD

**Issue by briand44** [ITS-UofIowa/sitenow_wysiwyg#21]
This message is displayed when clicking the paste from word icon.

Your browser doesn't allow you to paste this way. Press ⌘+V to paste.

**Comment by briand44** [comment]
This was reproduced using the nightly build http://nightly.ckeditor.com/17-06-15-06-08/full/samples/ as well as using a demo example with the standard ckeditor package so it shouldn't have anything to do with our setup.

**Comment by joewhitsitt** [comment]
Something on the web made me think I should try IE just in case. A dialog box popped up and asked if the clipboard should be accessed. I clicked 'allow,' but then the same CKEditor message popped up.

**Comment by genjohnson** [comment]
I was wondering if there was a change to a setting or policy with the University-managed computers blocking access to the clipboard, but I'm getting the same error message using the nightly build on my personal computer.

**Comment by briand44** [comment]
https://github.com/ckeditor/ckeditor-dev/issues/595

**Comment by briand44** [comment]
https://github.com/ckeditor/ckeditor-dev/issues/469

It doesn't look like ckeditor is planning on doing anything to fix this.

**Comment by genjohnson** [comment]
Until browsers provide an API to trigger the paste... https://github.com/ckeditor/ckeditor-dev/issues/469issuecomment-306279192

We may be waiting a while, so I motion to remove the paste buttons from the WYSIWYG.

**Comment by briand44** [comment]
I was thinking the same. Figured we can talk about this next Tuesday

**Comment by joewhitsitt** [comment]
The paste from word button has been removed. #30
